// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhotoPrint.API.Data;

#nullable disable

namespace PhotoPrint.API.Migrations
{
    [DbContext(typeof(PhotoPrintDbContext))]
    [Migration("20260521063322_AddProductCatalog")]
    partial class AddProductCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhotoPrint.API.Models.EmailConfirmationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_confirmation_tokens_user_id");

                    b.ToTable("EmailConfirmationTokens");
                });

            modelBuilder.Entity("PhotoPrint.API.Models.EmailQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextRetryAt")
                        .HasDatabaseName("ix_email_queue_status_next_retry");

                    b.ToTable("EmailQueue");
                });

            modelBuilder.Entity("PhotoPrint.API.Models.ExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique()
                        .HasDatabaseName("ix_external_logins_provider_key");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ix_external_logins_user_provider");

                    b.ToTable("ExternalLogins");
                });

            modelBuilder.Entity("PhotoPrint.API.Models.GuestSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClaimedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimedByUserId")
                        .HasDatabaseName("ix_guest_sessions_claimed_by_user");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_guest_sessions_expires_at");

                    b.ToTable("GuestSessions");
                });

            modelBuilder.Entity("PhotoPrint.API.Models.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("PhotoPrint.API.Models.PricingTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("MaxQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductSizeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductSizeId")
                        .HasDatabaseName("ix_pricing_tiers_product_size_id");

                    b.ToTable("PricingTiers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000001"),
                            MaxQuantity = 9,
                            MinQuantity = 1,
                            ProductSizeId = new Guid("b1000000-0000-0000-0000-000000000001"),
                            UnitPrice = 1.20m
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000002"),
                            MaxQuantity = 49,
                            MinQuantity = 10,
                            ProductSizeId = new Guid("b1000000-0000-0000-0000-000000000001"),
                            UnitPrice = 0.90m
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000003"),
                            MinQuantity = 50,
                            ProductSizeId = new Guid("b1000000-0000-0000-0000-000000000001"),
                            UnitPrice = 0.70m
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000004"),
                            MaxQuantity = 9,
                            MinQuantity = 1,
                            ProductSizeId = new Guid("b1000000-0000-0000-0000-000000000002"),
                            UnitPrice = 1.80m
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000005"),
                            MaxQuantity = 49,
                            MinQuantity = 10,
                            ProductSizeId = new Guid("b1000000-0000-0000-0000-000000000002"),
                            UnitPrice = 1.40m
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000006"),
                            MinQuantity = 50,
                            ProductSizeId = new Guid("b1000000-0000-0000-0000-000000000002"),
                            UnitPrice = 1.10m
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000007"),
                            MaxQuantity = 9,
                            MinQuantity = 1,
                            ProductSizeId = new Guid("b1000000-0000-0000-0000-000000000003"),
                            UnitPrice = 2.20m
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000008"),
                            MaxQuantity = 49,
                            MinQuantity = 10,
                            ProductSizeId = new Guid("b1000000-0000-0000-0000-000000000003"),
                            UnitPrice = 1.70m
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000009"),
                            MinQuantity = 50,
                            ProductSizeId = new Guid("b1000000-0000-0000-0000-000000000003"),
                            UnitPrice = 1.30m
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000010"),
                            MaxQuantity = 9,
                            MinQuantity = 1,
                            ProductSizeId = new Guid("b1000000-0000-0000-0000-000000000004"),
                            UnitPrice = 3.50m
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000011"),
                            MaxQuantity = 49,
                            MinQuantity = 10,
                            ProductSizeId = new Guid("b1000000-0000-0000-0000-000000000004"),
                            UnitPrice = 2.80m
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000012"),
                            MinQuantity = 50,
                            ProductSizeId = new Guid("b1000000-0000-0000-0000-000000000004"),
                            UnitPrice = 2.20m
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000013"),
                            MaxQuantity = 9,
                            MinQuantity = 1,
                            ProductSizeId = new Guid("b1000000-0000-0000-0000-000000000005"),
                            UnitPrice = 3.00m
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000014"),
                            MaxQuantity = 49,
                            MinQuantity = 10,
                            ProductSizeId = new Guid("b1000000-0000-0000-0000-000000000005"),
                            UnitPrice = 2.40m
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000015"),
                            MinQuantity = 50,
                            ProductSizeId = new Guid("b1000000-0000-0000-0000-000000000005"),
                            UnitPrice = 1.90m
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000016"),
                            MaxQuantity = 9,
                            MinQuantity = 1,
                            ProductSizeId = new Guid("b1000000-0000-0000-0000-000000000006"),
                            UnitPrice = 5.50m
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000017"),
                            MaxQuantity = 49,
                            MinQuantity = 10,
                            ProductSizeId = new Guid("b1000000-0000-0000-0000-000000000006"),
                            UnitPrice = 4.40m
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000018"),
                            MinQuantity = 50,
                            ProductSizeId = new Guid("b1000000-0000-0000-0000-000000000006"),
                            UnitPrice = 3.50m
                        });
                });

            modelBuilder.Entity("PhotoPrint.API.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "SortOrder")
                        .HasDatabaseName("ix_products_is_active_sort_order");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Poze foto",
                            ProductType = "PhotoPrint",
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("PhotoPrint.API.Models.ProductFinish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_finishes_product_id");

                    b.ToTable("ProductFinishes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000001"),
                            Name = "Lucioasă",
                            ProductId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000002"),
                            Name = "Mată",
                            ProductId = new Guid("a1000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("PhotoPrint.API.Models.ProductSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("HeightMm")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("WidthMm")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_sizes_product_id");

                    b.HasIndex("ProductId", "Label")
                        .IsUnique()
                        .HasDatabaseName("ix_product_sizes_product_id_label");

                    b.ToTable("ProductSizes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000001"),
                            HeightMm = 150,
                            IsActive = true,
                            Label = "10×15",
                            ProductId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            WidthMm = 100
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000002"),
                            HeightMm = 180,
                            IsActive = true,
                            Label = "13×18",
                            ProductId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            WidthMm = 130
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000003"),
                            HeightMm = 210,
                            IsActive = true,
                            Label = "15×21",
                            ProductId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            WidthMm = 150
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000004"),
                            HeightMm = 300,
                            IsActive = true,
                            Label = "20×30",
                            ProductId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            WidthMm = 200
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000005"),
                            HeightMm = 297,
                            IsActive = true,
                            Label = "A4",
                            ProductId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            WidthMm = 210
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000006"),
                            HeightMm = 420,
                            IsActive = true,
                            Label = "A3",
                            ProductId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            WidthMm = 297
                        });
                });

            modelBuilder.Entity("PhotoPrint.API.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_hash");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PhotoPrint.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("GdprConsentAccepted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PhotoPrint.API.Models.ExternalLogin", b =>
                {
                    b.HasOne("PhotoPrint.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhotoPrint.API.Models.GuestSession", b =>
                {
                    b.HasOne("PhotoPrint.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ClaimedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("PhotoPrint.API.Models.PricingTier", b =>
                {
                    b.HasOne("PhotoPrint.API.Models.ProductSize", "ProductSize")
                        .WithMany("PricingTiers")
                        .HasForeignKey("ProductSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSize");
                });

            modelBuilder.Entity("PhotoPrint.API.Models.ProductFinish", b =>
                {
                    b.HasOne("PhotoPrint.API.Models.Product", "Product")
                        .WithMany("Finishes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PhotoPrint.API.Models.ProductSize", b =>
                {
                    b.HasOne("PhotoPrint.API.Models.Product", "Product")
                        .WithMany("Sizes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PhotoPrint.API.Models.RefreshToken", b =>
                {
                    b.HasOne("PhotoPrint.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhotoPrint.API.Models.Product", b =>
                {
                    b.Navigation("Finishes");

                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("PhotoPrint.API.Models.ProductSize", b =>
                {
                    b.Navigation("PricingTiers");
                });
#pragma warning restore 612, 618
        }
    }
}
