// The gate vocabulary both drive halves share: the kinds the router prints as GATE_KIND and the
// answers the unattended policy is allowed to give. The router names a gate; the policy either has
// a written delegation for that kind or fails closed, so one list keeps the two sides in step.
// Reads nothing. Prose authorities that must change in the same commit as a change here: the
// gate-kind table in .claude/skills/loop-driver/SKILL.md and the policy vocabulary line in
// reviews/README.md (both generated by cli/docs-sync.mjs).

export const GATES = {
  loopClose: 'loop-close',
  deltaWorthiness: 'delta-worthiness',
  certificationGoAhead: 'certification-go-ahead',
  designPass: 'design-pass',
  noMetrics: 'no-metrics',
  recordsBroken: 'records-broken',
  noRowMatched: 'no-row-matched',
}

// Every answer the policy may print as NEXT. `<lens>` is filled in by the convergence blocker.
export const NEXT = {
  fixRound: 'fix round',
  deltaDiscovery: 'delta discovery',
  lensCoverage: 'lens-coverage discovery (<lens>)',
  certificationPair: 'certification (pair)',
  certificationSingle: 'certification (single)',
  closeLoop: 'close the loop',
}

export const POLICY_NEXT = Object.values(NEXT)

// One row per gate kind, in the order the router can reach them: what the router means by it and
// what the written delegation does with it. `delegated: false` = the policy stops on this kind.
export const GATE_DOCS = [
  { kind: GATES.loopClose, exit: 2, router: 'certification passed and no post-cert fix round is pending', policy: `auto — \`${NEXT.closeLoop}\` on the standing approval`, delegated: true },
  { kind: GATES.deltaWorthiness, exit: 3, router: 'the latest line is a clean verification', policy: `auto — \`${NEXT.deltaDiscovery}\` when the round fixed a 🔴, else the certification answer`, delegated: true },
  { kind: GATES.certificationGoAhead, exit: 2, router: 'loop quiet, nothing open, lens coverage complete', policy: `auto — \`${NEXT.certificationPair}\` or \`${NEXT.certificationSingle}\`, unless open work or a convergence blocker answers first`, delegated: true },
  { kind: GATES.designPass, exit: 2, router: 'two consecutive rounds seeded the same component at s ≥ 0.3', policy: 'stop — reimplementing a component is the owner\'s call', delegated: false },
  { kind: GATES.noMetrics, exit: 3, router: 'review files exist but there is no `metrics.jsonl`', policy: 'stop — no written delegation', delegated: false },
  { kind: GATES.recordsBroken, exit: 3, router: '`metrics.jsonl` carries no usable pass line', policy: 'stop — no written delegation', delegated: false },
  { kind: GATES.noRowMatched, exit: 3, router: 'no router row matched mechanically', policy: 'stop — no written delegation', delegated: false },
]
