#!/usr/bin/env node
// Ledger miner — ranks defect classes by measured cost, per the prevention sweep
// (docs/superpowers/specs/2026-08-10-prevention-sweep-design.md).
// Reads the class sidecar (reviews/state/defect-classes.jsonl) ONLY (never ledger prose); later line for the same
// (target, d) supersedes. Writes the ranked table into definition-of-done.md between
// <!-- miner:ranked-classes:start/end --> markers; --area <slug> prints a per-area ranking
// to stdout instead; --dry-run prints the table without writing.
//
// Usage: node reviews/lib/ledger-miner.mjs [--area <slug>] [--dry-run] [--root <repoRoot>]
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, relative } from 'node:path'
import { REPO as LIVE_REPO, DEFECT_CLASSES } from './records/schema.mjs'
import { repoRoot, takeRoot } from './cli/args.mjs'

const { root, rest: argv } = takeRoot(process.argv.slice(2))
let AREA = null, DRY = false
for (let i = 0; i < argv.length; i++) {
  if (argv[i] === '--area') AREA = argv[++i]
  else if (argv[i] === '--dry-run') DRY = true
}
const ROOT = repoRoot(import.meta.url, root)

const WEIGHT = { high: 5, medium: 3, low: 1, cleanup: 0.5 }
const sidecarPath = join(ROOT, relative(LIVE_REPO, DEFECT_CLASSES))
if (!existsSync(sidecarPath)) { console.error('ERROR   no reviews/state/defect-classes.jsonl — run the backfill first'); process.exit(1) }

const rows = new Map() // target/d -> row (later supersedes)
readFileSync(sidecarPath, 'utf8').split(/\r?\n/).filter(l => l.trim()).forEach((raw, i) => {
  let o
  try { o = JSON.parse(raw) } catch (e) { console.error(`ERROR   defect-classes.jsonl line ${i + 1}: ${e.message}`); process.exit(1) }
  for (const k of ['target', 'd', 'sev', 'class']) if (typeof o[k] !== 'string') { console.error(`ERROR   line ${i + 1}: missing "${k}"`); process.exit(1) }
  rows.set(`${o.target}/${o.d}`, o)
})

const pool = [...rows.values()].filter(r => !AREA || r.area === AREA)
const classes = new Map()
for (const r of pool) {
  const c = classes.get(r.class) ?? { count: 0, score: 0, sev: { high: 0, medium: 0, low: 0, cleanup: 0 }, targets: new Set(), examples: [] }
  c.count++
  c.score += WEIGHT[r.sev] ?? 0
  if (c.sev[r.sev] !== undefined) c.sev[r.sev]++
  c.targets.add(r.target)
  if (c.examples.length < 3 && (r.sev === 'high' || r.sev === 'medium')) c.examples.push(`${r.target.split('-')[0]}:${r.d}`)
  classes.set(r.class, c)
}
const ranked = [...classes.entries()].sort((a, b) => b[1].score - a[1].score)

const header = AREA ? `Area "${AREA}": ${pool.length} classified defects` : `${pool.length} classified defects across ${new Set(pool.map(r => r.target)).size} targets`
const lines = [
  `| Rank | Class | Score | 🔴 | 🟠 | 🟡 | ⚪ | Targets | Examples |`,
  `|---|---|---|---|---|---|---|---|---|`,
  ...ranked.map(([name, c], i) =>
    `| ${i + 1} | ${name} | ${c.score} | ${c.sev.high} | ${c.sev.medium} | ${c.sev.low} | ${c.sev.cleanup} | ${c.targets.size} | ${c.examples.join(' · ') || '—'} |`),
]
console.log(header + '\n' + lines.join('\n'))

if (AREA || DRY) process.exit(0)

const dodPath = join(ROOT, 'memory-bank', 'standards', 'definition-of-done.md')
const START = '<!-- miner:ranked-classes:start -->', END = '<!-- miner:ranked-classes:end -->'
const dod = readFileSync(dodPath, 'utf8')
if (!dod.includes(START) || !dod.includes(END)) { console.error('ERROR   definition-of-done.md has no miner:ranked-classes markers'); process.exit(1) }
const stamp = `_Generated by \`reviews/lib/ledger-miner.mjs\` from \`reviews/state/defect-classes.jsonl\` — ${header}. Score = 5·🔴 + 3·🟠 + 1·🟡 + 0.5·⚪. Do not hand-edit between the markers._`
const block = `${stamp}\n\n${lines.join('\n')}`
writeFileSync(dodPath, dod.slice(0, dod.indexOf(START) + START.length) + '\n' + block + '\n' + dod.slice(dod.indexOf(END)))
console.log(`\nnote    wrote ranked table into definition-of-done.md (${ranked.length} classes)`)
