#!/usr/bin/env node
// Validated worklog stamper: the only supported way to append an event to a target's
// worklog.jsonl. Owns the timestamp (ISO-8601 with the local UTC offset) and rejects a
// passed --t, enforces the event vocabulary and each event's required fields, and guards
// round-start/round-end pairing so only one round is open at a time. Resolves the target
// folder as reviews/<target> or reviews/archive/<target> (whichever exists), and only
// creates reviews/<target>/ fresh when neither does.
//
// Usage: node reviews/lib/wl.mjs [--root <repoRoot>] <target> <ev> [--<key> <value>]...
//          [--json '<obj>']
// Numeric-looking flag values become numbers; --ids comma-splits into an array (e.g.
// PPW-1,PPW-2); --json merges a raw object for fields flags can't express (e.g. nested
// "of"). Also exports appendEvent(root, target, event) for other lib scripts to call
// in-process; the CLI is a thin wrapper over it.
// Exit: 0 appended (prints the appended line) · 1 usage or validation error (prints
// "ERROR <reason>", appends nothing).
import { readFileSync, appendFileSync, existsSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { resolveDir, targetDirs } from './model/target.mjs'
import { repoRoot, takeRoot } from './cli/args.mjs'
import { EVENTS } from './records/schema.mjs'
import { deepEqual, live, readLines } from './records/worklog.mjs'

const VOCAB = new Set(Object.keys(EVENTS))
const IDS_EVENTS = new Set(Object.keys(EVENTS).filter(ev => EVENTS[ev].ids))

const TEST_KINDS = new Set(['red', 'green', 'final', 'baseline', 'revert-and-rerun'])
const PPW = /^PPW-\d+$/

// The stamper refuses to append against a log it cannot read whole: a line that is not JSON
// stops it, where a measuring reader would skip that line.
function readEvents(dir) {
  const lines = readLines(dir) ?? []
  for (const l of lines) if (l.error) throw l.error
  return lines.map(l => l.event)
}

function openRound(events) {
  let open = null
  for (const e of live(events)) {
    if (e.ev === 'round-start') open = e.round
    else if (e.ev === 'round-end' && e.round === open) open = null
  }
  return open
}

function closestTimestamps(events, tIso) {
  const target = Date.parse(tIso)
  return events.map(e => e.t)
    .filter(t => typeof t === 'string' && Number.isFinite(Date.parse(t)))
    .sort((a, b) => Math.abs(Date.parse(a) - target) - Math.abs(Date.parse(b) - target))
    .slice(0, 3)
}

function validateShape(event) {
  const { ev } = event
  for (const key of EVENTS[ev]?.required ?? []) {
    if (event[key] === undefined) throw new Error(`"${ev}" requires "${key}"`)
  }
  if (['round-start', 'round-end', 'triage-done', 'protocol-written', 'round-review-dispatched', 'round-review-returned', 'test-audit-dispatched', 'test-audit-returned'].includes(ev) && typeof event.round !== 'number') {
    throw new Error(`"${ev}" requires "round" to be a number`)
  }
  if (ev === 'test-run' && !TEST_KINDS.has(event.kind)) {
    throw new Error(`"test-run" requires "kind" to be one of ${[...TEST_KINDS].join('|')}`)
  }
  if ((ev === 'finding' || ev === 'verify-result') && !PPW.test(event.id)) {
    throw new Error(`"${ev}" requires "id" shaped like PPW-<n>`)
  }
  if (IDS_EVENTS.has(ev) && (!Array.isArray(event.ids) || event.ids.length === 0 || !event.ids.every(id => PPW.test(id)))) {
    throw new Error(`"${ev}" requires "ids" to be a non-empty array of PPW-<n> strings`)
  }
  if (ev === 'void') {
    const of_ = event.of
    if (typeof of_ !== 'object' || of_ === null || Array.isArray(of_) || of_.ev === undefined || of_.t === undefined) {
      throw new Error('"void" requires "of" to be an object with at least "ev" and "t"')
    }
  }
}

function nowIso() {
  const d = new Date()
  const pad = n => String(n).padStart(2, '0')
  const offMin = -d.getTimezoneOffset()
  const sign = offMin >= 0 ? '+' : '-'
  const abs = Math.abs(offMin)
  const off = `${sign}${pad(Math.floor(abs / 60))}:${pad(abs % 60)}`
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}${off}`
}

export function appendEvent(root, target, event) {
  if (!event || typeof event !== 'object') throw new Error('event must be an object')
  const { ev } = event
  if (!ev) throw new Error('missing "ev"')
  if (!VOCAB.has(ev)) throw new Error(`unknown ev "${ev}"`)
  if ('t' in event) throw new Error('"t" is generated by the stamper — a passed value is rejected')
  // Pass keys are numbers in the records; "v12" from a caller's prose is coerced, never stored.
  if (typeof event.pass === 'string' && /^v\d+$/.test(event.pass)) event = { ...event, pass: Number(event.pass.slice(1)) }
  validateShape(event)

  const reviewsDir = join(root, 'reviews')
  const candidateDirs = targetDirs(reviewsDir, target)
  const dir = resolveDir(reviewsDir, target) ?? candidateDirs[0]
  const wlPath = join(dir, 'worklog.jsonl')
  const existing = readEvents(dir)

  if (ev === 'round-start') {
    if (!existsSync(join(dir, `resolution-v${event.round}.md`))) {
      const label = dir === candidateDirs[1] ? `archive/${target}` : target
      throw new Error(`round-start ${event.round}: no resolution-v${event.round}.md in reviews/${label}/`)
    }
    const open = openRound(existing)
    if (open !== null) {
      throw new Error(`round-start ${event.round}: round ${open} is still open — stamp its round-end first (a re-start after round-end is how a multi-part round is recorded)`)
    }
  }
  if (ev === 'round-end') {
    const open = openRound(existing)
    if (open !== event.round) throw new Error(`round-end ${event.round}: no open round-start for ${event.round}`)
  }
  if (ev === 'void') {
    const match = existing.find(e => Object.keys(event.of).every(k => deepEqual(e[k], event.of[k])))
    if (!match) {
      const closest = closestTimestamps(existing, event.of.t)
      throw new Error(`void: no worklog event matches ${JSON.stringify(event.of)} — closest timestamps: ${closest.length ? closest.join(', ') : '(worklog is empty)'}`)
    }
  }

  const { ev: _ev, ...rest } = event
  const stamped = { t: nowIso(), ev, ...rest }
  mkdirSync(dir, { recursive: true })
  const prev = existsSync(wlPath) ? readFileSync(wlPath, 'utf8') : ''
  appendFileSync(wlPath, (prev && !prev.endsWith('\n') ? '\n' : '') + JSON.stringify(stamped) + '\n')
  return stamped
}

function coerce(v) {
  return /^-?\d+(\.\d+)?$/.test(v) ? Number(v) : v
}

function isMain() {
  return process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href
}

if (isMain()) {
  try {
    const { root: rootFlag, rest: argv } = takeRoot(process.argv.slice(2))
    const rest = []
    const event = {}
    for (let i = 0; i < argv.length; i++) {
      const a = argv[i]
      if (a === '--json') Object.assign(event, JSON.parse(argv[++i]))
      else if (a === '--ids') event.ids = argv[++i].split(',').map(s => s.trim()).filter(Boolean)
      else if (a.startsWith('--')) event[a.slice(2)] = coerce(argv[++i])
      else rest.push(a)
    }
    const root = repoRoot(import.meta.url, rootFlag)
    const [target, ev] = rest
    if (!target || !ev) {
      throw new Error("usage: wl.mjs [--root <repoRoot>] <target> <ev> [--<key> <value>]... [--json '<obj>']")
    }
    event.ev = ev
    const stamped = appendEvent(root, target, event)
    console.log(JSON.stringify(stamped))
    process.exit(0)
  } catch (e) {
    console.error(`ERROR ${e.message}`)
    process.exit(1)
  }
}
